name: 🤖👌🤖
on: pull_request

permissions:
  contents: write # zizmor: ignore[excessive-permissions]
  pull-requests: write # zizmor: ignore[excessive-permissions]
# checks: read # For private repositories
# actions: read # For private repositories

jobs:
  judge-dependabot:
    timeout-minutes: 5
    runs-on: ubuntu-slim
    outputs:
      merge: ${{ steps.conclusion.outputs.merge }}
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
      - name: Judge
        id: conclusion
        if: >-
          steps.dependabot.outputs.update-type != 'version-update:semver-major' ||
          contains(steps.dependabot.outputs.dependency-names, 'NixOS')
        run: echo -n 'merge=true' | tee -a "$GITHUB_OUTPUT"
  dependabot:
    needs: [judge-dependabot]
    if: ${{ needs.judge-dependabot.outputs.merge == 'true' }}
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - name: Wait for other jobs
        uses: kachick/wait-other-jobs@v4
        with:
          skip-same-workflow: 'true'
        timeout-minutes: 10
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ github.token }}

  # Avoid the "automerge" Renovate official feature.
  #   It takes a long time to be merged.
  # Avoid the "platformAutomerge" Renovate official feature.
  #   It requires many changes to GitHub settings.
  #    - `Allow auto-merge`
  #    - `Require status checks to pass before merging` and specify the status names
  #   Changing settings in all personal repositories is an annoying task for me.
  #   Even when using Terraform, retrieving mandatory CI names for each repository is too annoying!
  renovate:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
    steps:
      - name: Wait for other jobs
        uses: kachick/wait-other-jobs@v4
        with:
          skip-same-workflow: 'true'
        timeout-minutes: 10
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ github.token }}

  # https://github.com/kachick/anylang-template/issues/51
  selfup-runner:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.user.login == 'selfup-runner[bot]' }}
    steps:
      - name: Wait for other jobs
        uses: kachick/wait-other-jobs@v4
        with:
          skip-same-workflow: 'true'
        timeout-minutes: 20
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --delete-branch --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ github.token }}
